spring:
  data:
    redis:
      repositories:
        enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        dialect: io.tolgee.dialects.postgres.CustomPostgreSQLDialect
#  main:
#    lazy-initialization: true
tolgee:
  authentication:
    enabled: false
  postgres-autostart:
    enabled: true
  #    jwt-secret-file: /<user home>/.tolgee/jwt.secret
  #    jwt-secret: some long string
  #    jwt-expiration: 604800000
  #    native-enabled: true
  #    registrations-allowed: false
  #    initial-username: "admin"
  #    initial-password: "admin"
  #    github:
  #      client-id: <client id obtained from github>
  #      client-secret: <client secret obtained from github>
  #      authorization-url: "https://github.com/login/oauth/access_token"
  #      user-url: "https://api.github.com/user"
  #    ldap: ##experimental feature
  #      base-dn:
  #      enabled:
  #      port:
  #      principal-password:
  #      security-principal:
  #      urls:
  #      user-dn-pattern:
  #  smtp:
  #    from:
  #    host:
  #    password:
  #    smtp-auth:
  #    smtp-port:
  #    ssl-enabled:
  #    tls-enabled:
  #    tls-required:
  #    username:
  #  sentry:
  #    enabled: false
  #    dsn:
  cache:
    enabled: true
    use-redis: false
    default-ttl: 1200000
server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: 1024
  error:
    include-exception: false
    include-stacktrace: never
sentry:
  dsn: ${tolgee.sentry.server-dsn:}
management:
  health:
    ldap:
      enabled: false
    mail:
      enabled: false

